spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    username: root
    password: root1234!
    url: jdbc:mysql://localhost:3306/test
